### ISSUE TITLE
'releasing leaked death recipient' caused by gms.

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#29]
Please audit the gms code.
I see this on the console log when a room gets connected:

```
W/JavaBinder( 2154): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.gms.games.service.statemachine.roomclient.WaitServiceSetupState$1
```

It's an issue caused by com.google.android.gms

**Comment by stolk** [comment]
And here is the full log, for context.

Play Games version 
3.5.17 (2469365-030)

Android 4.4.4

gpg-cpp-sdk_2.0

```
I/swaag   (15688): StateManager::onNetworkMatch
I/RoomServiceClient( 2154): Creating RoomServiceClient and mStateMachine
D/ConnectivityManager( 2154): getActiveNetworkInfo : NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "Dutch", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/ActivityThread(15728): Added TimaKesytore provider
I/MultiDex(15728): VM with version 1.6.0 does not have multidex support
I/MultiDex(15728): install
I/MultiDex(15728): MultiDexExtractor.load(/data/app/com.google.android.gms-11.apk, false)
I/MultiDex(15728): loading existing secondary dex files
I/MultiDex(15728): load found 3 secondary dex files
I/MultiDex(15728): install done
V/JNIHelp (15728): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 254 native methods...
I/ProviderInstaller(15728): Installed default security provider GmsCore_OpenSSL
D/ChimeraCfgMgr(15728): Reading stored module config
D/WearableService( 1367): callingUid 10015, callindPid: 1367
E/MDM     ( 1367): [132] b.run: Couldn't connect to Google API client: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
D/ChimeraCfgMgr(15728): Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr(15728): Loading module APK com.google.android.play.games
D/LocationInitializer( 2154): Restart initialization of location
V/GLSActivity( 1486): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
V/libjingle(15728): JavaVM 0x417d0548
V/libjingle(15728): Games Libjingle native methods registered.
V/libjingle(15728): Games Libjingle native loaded.
I/libjingle(15728): static _jclass* games_rtmp::MetricsJniHelper::LookupJClass(JNIEnv*, const char*): Trying to find class: com/google/android/gms/games/jingle/PeerDiagnostics
I/libjingle(15728): static _jclass* games_rtmp::MetricsJniHelper::LookupJClass(JNIEnv*, const char*): Trying to find class: com/google/android/gms/games/jingle/PeerDiagnostics$AggregateStats
I/libjingle(15728): static _jclass* games_rtmp::MetricsJniHelper::LookupJClass(JNIEnv*, const char*): Trying to find class: com/google/android/gms/games/jingle/PeerDiagnostics$PeerChannelMetrics
V/libjingle(15728): Games Libjingle field(s) and method(s) cached.
V/GLSActivity( 1486): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
V/GLSActivity( 1486): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
D/NativeLibraryUtils(15728): Install completed successfully. count=14 extracted=0
I/libjingle(15728): Token type:OAuth2
I/libjingle(15728): Final XMPP server hostname talk.google.com port to 5222
I/libjingle(15728): OpenSSLAdapter::OnConnectEvent
I/libjingle(15728): BeginSSL: talk.google.com
I/libjingle(15728): Starting Jingle info task.
I/libjingle(15728): IbbDataTask::ProcessStart() called:
I/libjingle(15728): ProcessStart()::Sending Jingle info stanza.
I/libjingle(15728): BuzzSubscriptionsTask::SubscribeTask::ProcessStart() called:
I/libjingle(15728): void games_rtmp::BuzzSubscription::CheckOverride(): Channel GAMES_NOTIFICATION_CHANNEL default: games.google.com
I/libjingle(15728): void games_rtmp::BuzzSubscription::CheckOverride(): Notifier GAMES_NOTIFICATION_JID default: games@google.com
I/libjingle(15728): void games_rtmp::BuzzSubscription::CheckOverride(): Channel GAMES_BUZZBOT_CHANNEL default: games.google.com/buzzbot
I/libjingle(15728): void games_rtmp::BuzzSubscription::CheckOverride(): Notifier GAMES_BUZZBOT_JID default: play-presence@games.bot.talk.google.com
I/libjingle(15728): SUBSCRIBE STANZA: <cli:iq type="set" to="games@ob.talk.google.com" id="9" xmlns:cli="jabber:client"><subscribe xmlns="google:push"><item channel="games.google.com" from="games@google.com"/><item channel="games.google.com/buzzbot" from="play-presence@games.bot.talk.google.com"/></subscribe></cli:iq>
I/libjingle(15728): Send Stanza return ok:
I/libjingle(15728): OnJingleInfo called. Setting relay/stun hosts.
I/libjingle(15728): SubscribeTask HandleStanza : <cli:iq to="games@ob.talk.google.com/games_andr77BE0D04" from="games@ob.talk.google.com" id="9" type="result" xmlns:cli="jabber:client"/>
I/libjingle(15728): void games_rtmp::BuzzSubscriptionsTask::SubscriptionSuccess(): Subscription Successful.
D/ChimeraCfgMgr( 2154): Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr( 2154): Module APK com.google.android.play.games already loaded
D/ConnectivityManager( 2154): getActiveNetworkInfo : NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "Dutch", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
I/libjingle(15728): virtual int games_rtmp::BuzzSubscriptionsTask::SetOnDisconnectTask::ProcessStart(): Send-on-disconnect: <cli:message to="games@ob.talk.google.com" type="headline" xmlns:cli="jabber:client"><push xmlns="google:push" channel="games.google.com/buzzbot" sendOnDisconnect="true"><recipient to="play-presence@games.bot.talk.google.com">Q2hvS0NRajFqT1hubWhzUUFoQUJHQUVnX19fX19fX19fX19fQVJDNmtNU3FucTdqemtJOmdhbWVzQG9iLnRhbGsuZ29vZ2xlLmNvbS9nYW1lc19hbmRyNzdCRTBEMDQ=</recipient></push></cli:message>
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
I/swaag   (15688): created a room. Valid() returns 1
E/Parcel  (  965): Class not found when unmarshalling: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  965): java.lang.ClassNotFoundException: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  965): 	at java.lang.Class.classForName(Native Method)
E/Parcel  (  965): 	at java.lang.Class.forName(Class.java:251)
E/Parcel  (  965): 	at java.lang.Class.forName(Class.java:216)
E/Parcel  (  965): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
E/Parcel  (  965): 	at android.os.Parcel.readParcelable(Parcel.java:2097)
E/Parcel  (  965): 	at android.os.Parcel.readValue(Parcel.java:2013)
E/Parcel  (  965): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
E/Parcel  (  965): 	at android.os.Bundle.unparcel(Bundle.java:249)
E/Parcel  (  965): 	at android.os.Bundle.getString(Bundle.java:1118)
E/Parcel  (  965): 	at android.content.Intent.getStringExtra(Intent.java:5285)
E/Parcel  (  965): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1586)
E/Parcel  (  965): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1167)
E/Parcel  (  965): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4507)
E/Parcel  (  965): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4389)
E/Parcel  (  965): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:161)
E/Parcel  (  965): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3013)
E/Parcel  (  965): 	at android.os.Binder.execTransact(Binder.java:404)
E/Parcel  (  965): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  (  965): Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/games/multiplayer/realtime/RoomEntity
E/Parcel  (  965): 	... 18 more
E/Parcel  (  965): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.multiplayer.realtime.RoomEntity" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  (  965): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  (  965): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/Parcel  (  965): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/Parcel  (  965): 	... 18 more
V/ApplicationPolicy(  965): isApplicationStateBlocked userId 0 pkgname com.google.android.play.games
W/ActivityManager(  965): mDVFSHelper.acquire()
I/swaag   (15688): CMD_PAUSE handled
I/swaag   (15688): CMD_LOST_FOCUS handled
I/swaag   (15688): State saved
D/ActivityThread(15758): Added TimaKesytore provider
I/swaag   (15688): Participant Status Changed for id p_CIWl1PDOgOjxDRAB(not connected), name Player 6152, room status , participant status CONNECTING
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
I/swaag   (15688): Room Status Changed for room id ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, status (id: ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, creation time: 1454609720877 ms, creating participant: (name: Bram Stolk, id: p_CLqQxKqeruPOQhAB, has player: true, player: (id: 110078821488315885564, name: Bram Stolk), status: JOINED, has match result: false, match result: NONE, match rank: 0), status: CONNECTING, description: (null), free automatching slots: 1, variant: 1, automatch wait estimate: 9 ms).
D/Activity(15758): #1 setTransGradationModeColor false
I/Adreno-EGL(15758): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL(15758): OpenGL ES Shader Compiler Version: E031.24.02.11
I/Adreno-EGL(15758): Build Date: 09/12/14 Fri
I/Adreno-EGL(15758): Local Branch: LA.3.6.1_20140912_070_patches
I/Adreno-EGL(15758): Remote Branch: 
I/Adreno-EGL(15758): Local Patches: 
I/Adreno-EGL(15758): Reconstruct Branch: 
D/OpenGLRenderer(15758): Enabling debug mode 0
W/View    (15758): requestLayout() improperly called by android.view.View{42293920 V.ED.... ......I. 0,0-0,0 #7f0d0324 app:id/header_shadow} during layout: running second layout pass
W/GamesServiceBroker( 2154): Client connected with SDK 8283000, Services 8489030, and Games 35170030
D/ChimeraCfgMgr( 2154): Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr( 2154): Module APK com.google.android.play.games already loaded
V/BaseAuthAsyncOperation( 2154): All scopes had been granted in the past, skip access token fetching
V/BaseAuthAsyncOperation( 2154): access token request successful
I/WaitingRoom(15758): Room status after registering listener: 2
W/BaseAppContext( 2154): Using Auth Proxy for data requests.
W/ActivityManager(  965): mDVFSHelper.release()
I/libjingle(15728): Parsing Jingle data content
I/libjingle(15728): void gtalk::LibjingleClient::OnCallCreate(cricket::Call*): Connecting to OnAddSession
I/libjingle(15728): Calling Call::IncomingSession()
I/libjingle(15728): AddSession() called. has_data = 1
I/libjingle(15728): Creating data channel.
I/libjingle(15728): Is worker current:0
I/libjingle(15728): Current thread:0x7bfaf110
I/libjingle(15728): worker_thread:0x7bfaf488 initialized=1
I/libjingle(15728): Created channel for data
I/libjingle(15728): DataChannel::Init() called
I/libjingle(15728): Setting remote data description
I/libjingle(15728): Added data recv stream '' with ssrc=79270269
I/libjingle(15728): Add remote ssrc: 79270269
I/libjingle(15728): DataMediaChannel::SetSendBandwidth to 10485000bps.
I/libjingle(15728): Changing data state, recv=0 send=0
I/libjingle(15728): result = 1
I/libjingle(15728): void gtalk::LibjingleClient::OnAddSession(cricket::Call*, cricket::Session*): OnAddSession called.
I/libjingle(15728): Setting local data description
I/libjingle(15728): Added data send stream '' with ssrc=1578575759
I/libjingle(15728): Add send ssrc: 1578575759
I/libjingle(15728): SRTP reset to init state
I/libjingle(15728): Changing data state, recv=0 send=0
I/libjingle(15728): Network Information: All networks
I/libjingle(15728): Name, Description, Prefix, Prefix Length, IP, ignored
I/libjingle(15728): ipv4-default default IPV4 network 0.0.0.0 32 10.0.1.27 0
I/libjingle(15728): wlan0 wlan0 10.0.1.0 24 10.0.1.27 0
I/libjingle(15728): p2p0 p2p0 fe80:: 64 fe80::485a:3fff:fe5d:dd44 0
I/libjingle(15728): wlan0 wlan0 fe80:: 64 fe80::4a5a:3fff:fe5d:dd44 0
I/libjingle(15728): 
I/libjingle(15728): Channel enabled
I/libjingle(15728): Changing data state, recv=1 send=0
I/libjingle(15728): HttpRequest start: relay.google.com/create_session?username=ioDPQTlGFnVeK3Vr&password=XvYoQ1l9CVygXmdc8qTnd2eT&sn=3
I/libjingle(15728): SSL Cleanup
E/libjingle(15728): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22
E/libjingle(15728): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22
E/libjingle(15728): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22
E/libjingle(15728): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22
I/libjingle(15728): OpenSSLAdapter::OnConnectEvent
I/libjingle(15728): BeginSSL: relay.google.com
I/libjingle(15728): HttpRequest completed successfully
I/libjingle(15728): SSL Cleanup
E/libjingle(15728): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22
E/libjingle(15728): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22
I/libjingle(15728): Channel socket writable (data_rtp) for the first time
I/libjingle(15728): Changing data state, recv=1 send=1
I/swaag   (15688): P2P Connected. (Room id ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI w. status (id: ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, creation time: 1454609720877 ms, creating participant: (name: Bram Stolk, id: p_CLqQxKqeruPOQhAB, has player: true, player: (id: 110078821488315885564, name: Bram Stolk), status: JOINED, has match result: false, match result: NONE, match rank: 0), status: CONNECTING, description: (null), free automatching slots: 1, variant: 1, automatch wait estimate: 9 ms))
D/ChimeraCfgMgr( 2154): Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr( 2154): Module APK com.google.android.play.games already loaded
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
I/swaag   (15688): The Connected Set Changed for room id ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, status . Currently connected: 2
I/swaag   (15688): The Connected Set Changed for room id ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, status . Currently connected: 2
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
I/WaitingRoom(15758): CALLBACK: onRoomConnected()...
I/WaitingRoom(15758): onRoomConnected: statusCode = 0 for room ID: ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI
W/JavaBinder( 2154): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.gms.games.service.statemachine.roomclient.WaitServiceSetupState$1
I/swaag   (15688): CMD_GAINED_FOCUS handled
W/ActivityManager(  965): mDVFSHelper.acquire()
D/BuggyActivity(15688): onActivityResult(4673607,-1,Intent { (has extras) }
V/GamesNativeSDK(15688): Received OnActivityResult with result_code: -1
I/swaag   (15688): Succesfully showed room [ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI] (created by Bram Stolk): (null)
I/swaag   (15688): Participant named Bram Stolk(connected), id p_CLqQxKqeruPOQhAB, status (name: Bram Stolk, id: p_CLqQxKqeruPOQhAB, has player: true, player: (id: 110078821488315885564, name: Bram Stolk), status: JOINED, has match result: false, match result: NONE, match rank: 0)
I/swaag   (15688): Participant named Player 6152(connected), id p_CIWl1PDOgOjxDRAB, status (name: Player 6152, id: p_CIWl1PDOgOjxDRAB, has player: false, player: (Invalid Player), status: JOINED, has match result: false, match result: NONE, match rank: 0)
V/GamesNativeSDK(15688): Received Activity Resume Event.
D/Activity(15688): #3 setTransGradationModeColor to false
D/Activity(15688): #4 setTransGradationMode to false:
E/GamesNativeSDK(15688): Sending reliable message
I/swaag   (15688): Starting round 0 with map 0
I/swaag   (15688): geomdb cleared of 0 entries (0 evicted from cache).
I/swaag   (15688): randomseeds d5 0, skip 5
E/GamesNativeSDK(15688): Sending reliable message SUCCEEDED
I/swaag   (15688): world created for level -1
I/swaag   (15688): objectOfInterest at 0x793f3858 named 'player'
I/swaag   (15688): CMD_RESUME handled
I/ActivityManager(  965): Killing 15151:com.samsung.android.provider.filterprovider/u0a116 (adj 15): empty #43
D/ChimeraCfgMgr( 2154): Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr( 2154): Module APK com.google.android.play.games already loaded
I/libjingle(15728): IbbDataTask::ProcessStart() called:
I/libjingle(15728): Got Xmpp data back: <ibb:data ibb:seq="0" ibb:sid="1" xmlns:ibb="http://jabber.org/protocol/ibb"/>
I/libjingle(15728): static void gtalk::LibjingleJniHelper::DispatchIbbSendResult(jobject, const string&, const string&, bool): Dispatch ID:1
I/libjingle(15728): IbbDataTask::ProcessStart() called:
I/RoomServiceStateMachine(15728): Attempting to reconnect to: p_CIWl1PDOgOjxDRAB
I/RoomServiceStateMachine(15728): Reestablished peer connection to p_CIWl1PDOgOjxDRAB after 1 tries
I/swaag   (15688): P2P Connected. (Room id ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI w. status (id: ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, creation time: 1454609720877 ms, creating participant: (name: Bram Stolk, id: p_CLqQxKqeruPOQhAB, has player: true, player: (id: 110078821488315885564, name: Bram Stolk), status: JOINED, has match result: false, match result: NONE, match rank: 0), status: ACTIVE, description: (null), free automatching slots: 1, variant: 1, automatch wait estimate: 9 ms))
I/libjingle(15728): worker_thread:0x7bfaf488 initialized=1
I/libjingle(15728): Channel disabled
I/libjingle(15728): Changing data state, recv=0 send=0
I/libjingle(15728): Destroyed channel
I/RoomServiceStateMachine(15728): Current status version 4 which is the same or later than the version received 4. Ignoring the notification.
W/ActivityManager(  965): mDVFSHelper.release()
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
I/swaag   (15688): The Connected Set Changed for room id ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, status . Currently connected: 0
I/swaag   (15688): No more people here, we might as well leave and close that room now.
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
I/swaag   (15688): Participant Status Changed for id p_CIWl1PDOgOjxDRAB(not connected), name Player 6152, room status (id: ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, creation time: 1454609720877 ms, creating participant: (name: Bram Stolk, id: p_CLqQxKqeruPOQhAB, has player: true, player: (id: 110078821488315885564, name: Bram Stolk), status: JOINED, has match result: false, match result: NONE, match rank: 0), status: ACTIVE, description: (null), free automatching slots: 1, variant: 1, automatch wait estimate: 9 ms), participant status (name: Player 6152, id: p_CIWl1PDOgOjxDRAB, has player: false, player: (Invalid Player), status: LEFT, has match result: false, match result: NONE, match rank: 0)
I/swaag   (15688): The Connected Set Changed for room id ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, status (id: ChoKCQj1jOXnmhsQAhABGAEg____________ARC6kMSqnq7jzkI, creation time: 1454609720877 ms, creating participant: (name: Bram Stolk, id: p_CLqQxKqeruPOQhAB, has player: true, player: (id: 110078821488315885564, name: Bram Stolk), status: JOINED, has match result: false, match result: NONE, match rank: 0), status: ACTIVE, description: (null), free automatching slots: 1, variant: 1, automatch wait estimate: 9 ms). Currently connected: 0
I/swaag   (15688): No more people here, we might as well leave and close that room now.
D/ConnectivityManager(15728): getActiveNetworkInfo : NetworkInfo: type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "Dutch", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
W/AppOps  (  965): Bad call: specified package com.google.android.play.games under uid 10255 but it is really 10153
D/ChimeraCfgMgr( 2154): Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr( 2154): Module APK com.google.android.play.games already loaded
I/swaag   (15688): We failed to leave the the room.
I/swaag   (15688): We left the room.
```

**Comment by binarynoise** [comment]
Also caused by `com.google.android.play.core.internal.ac`

**Comment by Okladnoj** [comment]
**I am using app evaluation package:**
`in_app_review: ^ 2.0.0-nullsafety`

```
void didChangeDependencies() {
    try {
      _inAppReview.isAvailable().then(
            (bool isAvailable) => setState(
              () => _isAvailable = isAvailable,
            ),
          );
    } catch (e) {
      setState(() => _isAvailable = false);
    }

    super.didChangeDependencies();
  }
```
I get such a terrible error log !!! (((

```
I/InAppReviewPlugin( 8791): isAvailable: called
I/InAppReviewPlugin( 8791): isAvailable: playStoreInstalled: true
I/InAppReviewPlugin( 8791): isAvailable:lollipopOrLater: true
I/InAppReviewPlugin( 8791): isAvailable: The Play Store is available and Android 5 or later is being used
I/InAppReviewPlugin( 8791): cacheReviewInfo: called
I/PlayCore( 8791): UID: [10937]  PID: [8791] ReviewService : requestInAppReview (radio.radiogram)
I/InAppReviewPlugin( 8791): cacheReviewInfo: Requesting review flow
I/PlayCore( 8791): UID: [10937]  PID: [8791] ReviewService : Initiate binding to the service.
I/PlayCore( 8791): UID: [10937]  PID: [8791] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore( 8791): UID: [10937]  PID: [8791] ReviewService : linkToDeath
I/PlayCore( 8791): UID: [10937]  PID: [8791] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
I/PlayCore( 8791): UID: [10937]  PID: [8791] ReviewService : Unbind from service.
I/InAppReviewPlugin( 8791): onComplete: Successfully requested review flow
W/JavaBinder( 8791): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.core.internal.ai
```

**Comment by deremakif** [comment]
still have the issue!

**Comment by DNK-Creator** [comment]
> still have the issue!

Lmaoo no one really replied after 5 years

**Comment by Karlomanio** [comment]
I didn't know that computers had a "Link to Death."  I thought it was only humans that had that... lmao.

**Comment by rajput-abdullah** [comment]
I'm facing the same issue mentioned above currently in Android 11, Flutter version 3.30, InAppReview version 2.0.4 
Is anybody currently facing this issue in flutter?

**Comment by smile616** [comment]
RoomServiceClient is deprecated, don't use it.

in_app_review is not part of the cpp-android-basic-samples nor Play Games services offering. Please file bugs for in_app_review in the in_app_review issue tracker.

linkToDeath is part of Android IPC. It allows one process receive a call in case "linked" process was killed. See https://developer.android.com/reference/android/os/IBinder#linkToDeath(android.os.IBinder.DeathRecipient,%20int)
